################################################################################
##
## Filename: Makefile
## Project:	 Constrained Random Pattern Generation
##
## Creator:	 Dhgir.Abine@gmail.com
##
################################################################################

default: all

DUT := zipsystem

include ../Makefile
